### ISSUE TITLE
Windows tests with single GPU on circle CI

### ISSUE THREAD

**Issue by sdesrozis** [pytorch/ignite#1431]
## 🚀 Feature

Need #1430 resolved first.

Add windows test with single GPU on circle CI.

**Comment by vfdev-5** [comment]
This can be done with 
```
  windows-gpu:
    machine:
      resource_class: windows.gpu.nvidia.medium
      image: windows-server-2019-nvidia:stable
      shell: bash.exe
```
added to https://github.com/pytorch/ignite/blob/master/.circleci/config.yml#L17
