### ISSUE TITLE
Update CONTRIBUTING and pre-commit file

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1618]
Seems like these lines should be updated in order to reflect the latest state of things:
- https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md#formatting-without-pre-commit
```diff
- isort -rc .
- black .
+ black .
+ isort .
```
and
https://github.com/pytorch/ignite/blob/29a436fac250bbec2ead8857cdd38b40ae5b8b41/.pre-commit-config.yaml#L23
should be updated to `5.7.0` release (to check the exact change).

cc @Devanshu24 I remember you are using pre-commit, could you please take a look at this issue. Thanks!

**Comment by Devanshu24** [comment]
Sure, I'll get to it! :)

**Comment by Devanshu24** [comment]
I went through the other hooks in `pre-commit` too and a most of them have new versions available(without breaking changes), should we update them too?
Also after changing these versions and running `pre-commit run --all-files` there are a lot of changes that take place, do we want that too happen?
Some of those changes include:
- A _lot_ of new lines at the end for markdowns, svgs, other files
- Formatting the example files too
- Removing whitespaces
- Using `-` instead of `*` for unordered lists
- etc.

Final stats of file changes is such
```bash
$ git diff --shortstat upstream/master 
139 files changed, 1438 insertions(+), 513 deletions(-)
```
___


The new `.pre-commit-config.yaml` looks like this

```yaml
exclude: "^conda.recipe"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--append-config=tox.ini]

```
