### ISSUE TITLE
Automatic deployment on tag

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#248]
Travis with PyPI: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by vfdev-5** [comment]
PyPI wheels+tars build and upload can be done as following:
```
# PyPI Deployment: https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: vfdev-5
  # If password contains non alphanumeric characters
  # https://github.com/travis-ci/dpl/issues/377
  # pass it as secured variable
  password: $PYPI_TOKEN
  # otherwise, follow "How to encrypt the password": https://docs.travis-ci.com/user/encryption-keys/
  # `travis encrypt deploy.password="password"`
#    secure: "secured_password"

  # !!! This can be removed if deploy on PyPI
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.5"
```
A test result is [here](https://test.pypi.org/manage/project/pytorch-ignite/release/0.1.0.2/)


Note that user and password should be specified and password is passed as secure Travis variable. I did not manage to handle password encryption.

Conda build and upload can be done in the phase "after_deploy". Need to be scripted and tested
