### ISSUE TITLE
CPU conda package

### ISSUE THREAD

**Issue by jamesmyatt** [pytorch/ignite#485]
Is there any chance of a conda package that depends on pytorch-cpu instead? Or am I missing something?

**Comment by vfdev-5** [comment]
@jamesmyatt in this case, probably, you can install `pytorch-cpu` at first and then install `ignite` without dependencies:
```bash
conda install pytorch-cpu -c pytorch
conda install ignite -c pytorch --no-deps
```
HTH

**Comment by jamesmyatt** [comment]
Does that work in an environment.yml file? i.e. can I add `pytorch::ignite --no-deps`?

**Comment by vfdev-5** [comment]
@jamesmyatt probably your issue is a duplicate of https://github.com/conda/conda/issues/7911
I think there is no flag like that in yml. Even if you install packages like proposed above and then export  the environment into `yml`, it is not possible to create new environment with `pytorch-cpu` and `ignite` that does not bring `pytorch`...

**Comment by jamesmyatt** [comment]
Agreed. I think it's the same as that conda issue.

**Comment by vfdev-5** [comment]
@jamesmyatt the following yaml can probably solve your problem:
```yaml
name: pytorch-ignite-cpu
channels:
  - pytorch
dependencies:
  - python=3.6
  - pip:    
    - https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
    - torchvision
    - pytorch-ignite
```
